# Generated by Django 4.2.7 on 2023-11-22 13:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import e_books_online_store.accounts.models
import e_books_online_store.accounts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': 'User with this email address already exists!'}, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_buy', models.BooleanField(default=True)),
                ('can_sell', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_last_name', models.CharField(blank=True, max_length=65, null=True, validators=[e_books_online_store.accounts.validators.only_letters, django.core.validators.MinLengthValidator(2)])),
                ('delivery_address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images', validators=[e_books_online_store.accounts.validators.image_size])),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', e_books_online_store.accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='storeuser',
            name='groups',
            field=models.ManyToManyField(through='accounts.GroupMembership', to='auth.group'),
        ),
    ]
