# Generated by Django 4.2.7 on 2023-12-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='liked_books',
            field=models.ManyToManyField(related_name='liked_by_users', to='books.book'),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='owned_books',
            field=models.ManyToManyField(related_name='owned_by_users', to='books.book'),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
