# Generated by Django 4.2.7 on 2024-01-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author_delete_author'),
        ('accounts', '0004_storeselleruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeselleruser',
            name='owned_books',
            field=models.ManyToManyField(related_name='owned_by_seller', to='books.book'),
        ),
    ]
