# Generated by Django 4.2.7 on 2024-01-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_storeselleruser_owned_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeselleruser',
            old_name='owned_books',
            new_name='listed_books',
        ),
    ]
