# Generated by Django 4.2.7 on 2024-01-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_owned_books_storeselleruser_listed_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeselleruser',
            name='listed_books',
        ),
    ]
