# Generated by Django 4.2.7 on 2024-01-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_storeselleruser_listed_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeselleruser',
            name='stripe_id',
            field=models.CharField(default='some_id', max_length=200),
            preserve_default=False,
        ),
    ]
