# Generated by Django 4.2.7 on 2024-01-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.CharField(choices=[("Children's books", "Children's books"), ('Family and Hobby', 'Family and Hobby'), ('Encyclopedias', 'Encyclopedias'), ('Fiction', 'Fiction'), ('Art', 'Art'), ('Economics and Business', 'Economics and Business'), ('History and politics', 'History and politics'), ('Teen', 'Teen'), ('Psychology and Philosophy', 'Psychology and Philosophy'), ('Fantasy', 'Fantasy'), ('Health and Beauty', 'Health and Beauty'), ('Personal Development', 'Personal Development'), ('Other', 'Other')], default=None),
        ),
    ]
