# Generated by Django 4.2.7 on 2024-01-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_sales_remove_book_genres_delete_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=70),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
