# Generated by Django 4.2.7 on 2024-01-19 15:39

from django.db import migrations, models
import e_books_online_store.books.validators


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='book_images/', validators=[e_books_online_store.books.validators.book_image_size]),
        ),
    ]
