# Generated by Django 4.2.7 on 2024-01-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.FileField(null=True, upload_to='books_pdf/'),
        ),
    ]
