# Generated by Django 4.2.7 on 2024-01-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_storeselleruser_listed_books'),
        ('books', '0005_book_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listed_books', to='accounts.storeselleruser'),
            preserve_default=False,
        ),
    ]
